package test.com.eddo.main;

import com.eddo.menu.EventMenu;
import com.eddo.menu.MainForm;
import com.eddo.menu.MenuItem;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import icon.tools.BufferedImageIO;
import jiconfont.icons.font_awesome.FontAwesome;
import test.com.eddo.form.Form1;
import view.iconmaker.IconFontGenerator;
import view.tools.Tools;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 *
 * @author raven
 */
public class MainTools extends javax.swing.JPanel {

	/**
	 * Creates new form Main
	 */
	public MainTools() {
		initComponents();
		mainForm.displayForm(new Tools().home());
		menu.addEventMenuSelected(new EventMenu() {
			@Override
			public void mainMenuSelected(MainForm mainForm, int index, MenuItem menuItem) {
				if (index == 0) {
					subMenu.setBorder(new TitledBorder("Connection"));
				} else {
					subMenu.setBorder(new TitledBorder("Menu-"));
				}
			}

			@Override
			public void subMenuSelected(MainForm mainForm, int index, int subMenuIndex, Component menuItem) {

				if (index == 0 && subMenuIndex == 0) {
					mainForm.displayForm(new Tools().sqlConnector());
				} else {
					mainForm.displayForm(new Form1("Form " + index + "-" + subMenuIndex));

				}

			}
		});
		// menu.setSelectedIndex(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		subMenu = new com.eddo.menu.SubMenuPanel();
		menu = new com.eddo.menu.Menu();
		lbLogo = new javax.swing.JLabel();
		mainMenuItem1 = new com.eddo.menu.MenuItem();
		mainMenuItem3 = new com.eddo.menu.MenuItem();
		mainMenuItem2 = new com.eddo.menu.MenuItem();
		mainMenuItem4 = new com.eddo.menu.MenuItem();
		mainMenuItem5 = new com.eddo.menu.MenuItem();
		mainForm = new com.eddo.menu.MainForm();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		chDarkMode = new javax.swing.JCheckBoxMenuItem();

		subMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(80, 1, 1, 1));

		menu.setMainForm(mainForm);
		menu.setSubMenuPanel(subMenu);

		lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbLogo.setIcon(new IconFontGenerator(FontAwesome.WRENCH, 40, null).getIcon());
		// lbLogo.setIcon(new
		// javax.swing.ImageIcon(getClass().getResource(path+"logo.png"))); // NOI18N
		lbLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		lbLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		menu.add(lbLogo);
		// mainMenuItem1.setBackground(new java.awt.Color(255, 45, 185));
		mainMenuItem1.setBackground(Color.DARK_GRAY);
		mainMenuItem1.setForeground(new java.awt.Color(75, 0, 243));
		mainMenuItem1.setIcon(getIcon("menu1")); // NOI18N
		mainMenuItem1.setMenuIcon(new javax.swing.AbstractListModel() {
			String[] strings = { "s1_1.png", "s1_2.png", "s1_3.png", "s1_4.png", "s1_5.png", "s1_6.png", "s1_7.png" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		mainMenuItem1.setMenuModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Connection mySQL", "Buttons", "Cards", "Tabs", "Accordions", "Modals",
					"Lists & Media Object" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		menu.add(mainMenuItem1);

		mainMenuItem3.setBackground(new java.awt.Color(0, 217, 64));
		mainMenuItem3.setForeground(new java.awt.Color(74, 74, 74));
		mainMenuItem3.setIcon(getIcon("menu2")); // NOI18N
		mainMenuItem3.setMenuIcon(new javax.swing.AbstractListModel() {
			String[] strings = { "s2_1.png", "s2_2.png", "s2_3.png", "s2_4.png", "s2_5.png" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		mainMenuItem3.setMenuModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Grid", "Progress Bars", "Notifications & Alerts", "Pagination", "Carousel" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		menu.add(mainMenuItem3);

		mainMenuItem2.setBackground(new java.awt.Color(255, 0, 0));
		mainMenuItem2.setForeground(new java.awt.Color(241, 255, 0));
		mainMenuItem2.setIcon(getIcon("menu3")); // NOI18N
		mainMenuItem2.setMenuIcon(new javax.swing.AbstractListModel() {
			String[] strings = { "s3_1.png", "s3_2.png", "s3_3.png" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		mainMenuItem2.setMenuModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Charts", "Morris", "Flot" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		menu.add(mainMenuItem2);

		mainMenuItem4.setBackground(new java.awt.Color(8, 191, 196));
		mainMenuItem4.setForeground(new java.awt.Color(3, 66, 178));
		mainMenuItem4.setIcon(getIcon("menu4")); // NOI18N
		mainMenuItem4.setMenuIcon(new javax.swing.AbstractListModel() {
			String[] strings = { "s4_1.png", "s4_2.png", "s4_3.png" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		mainMenuItem4.setMenuModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Maps", "Google Maps", "Vector Maps" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		menu.add(mainMenuItem4);

		mainMenuItem5.setBackground(new java.awt.Color(0, 225, 100));
		mainMenuItem5.setForeground(new java.awt.Color(178, 17, 225));
		mainMenuItem5.setIcon(getIcon("menu5")); // NOI18N
		mainMenuItem5.setText("mainMenuItem5");
		menu.add(mainMenuItem5);

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		jMenu3.setText("Options");

		chDarkMode.setText("Dark Mode");
		chDarkMode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chDarkModeActionPerformed(evt);
			}
		});
		jMenu3.add(chDarkMode);

		jMenuBar1.add(jMenu3);

//        setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addComponent(subMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(mainForm,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
								.addComponent(menu, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
								.addComponent(subMenu, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addContainerGap()));

//        pack();
//        setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void chDarkModeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chDarkModeActionPerformed
		if (chDarkMode.isSelected()) {
			EventQueue.invokeLater(() -> {
				FlatAnimatedLafChange.showSnapshot();
				FlatDarculaLaf.setup();
				FlatLaf.updateUI();
				FlatAnimatedLafChange.hideSnapshotWithAnimation();
			});
		} else {
			EventQueue.invokeLater(() -> {
				FlatAnimatedLafChange.showSnapshot();
				FlatIntelliJLaf.setup();
				FlatLaf.updateUI();
				FlatAnimatedLafChange.hideSnapshotWithAnimation();
			});
		}
	}

	Icon getIcon(String name) {
		return new BufferedImageIO().getIcon(20, 20, name + ".png");
	}
	// GEN-LAST:event_chDarkModeActionPerformed

//	public static void main(String args[]) {
//		FlatLaf.registerCustomDefaultsSource("com.eddo.style");
//		FlatIntelliJLaf.setup();
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				JFrame frame = new JFrame();
//				frame.setLayout(new BorderLayout());
//				frame.add(new MainTools());
//				frame.setVisible(true);
//				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//
//			}
//		});
//	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBoxMenuItem chDarkMode;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JLabel lbLogo;
	private com.eddo.menu.MainForm mainForm;
	private com.eddo.menu.MenuItem mainMenuItem1;
	private com.eddo.menu.MenuItem mainMenuItem2;
	private com.eddo.menu.MenuItem mainMenuItem3;
	private com.eddo.menu.MenuItem mainMenuItem4;
	private com.eddo.menu.MenuItem mainMenuItem5;
	private com.eddo.menu.Menu menu;
	private com.eddo.menu.SubMenuPanel subMenu;
	// End of variables declaration//GEN-END:variables

}
